module.exports = {
    switchState: require('./television/livebox.switchState'),
    pause : require('./television/livebox.pause'),
	play : require('./television/livebox.play'),
	stop : require('./television/livebox.stopMedia'),
	rewind : require('./television/livebox.rewind'),
	fastForward : require('./television/livebox.fastForward'),
    volumeUp : require('./television/livebox.volumeUp.js'),
    volumeDown : require('./television/livebox.volumeDown.js'),
    setVolume : require('./television/livebox.setVolume'),
    getVolume : require('./television/livebox.getVolume'),
    setMuted : require('./television/livebox.setMuted'),
    setChannel : require('./television/livebox.setChannel'),
    pressKey : require('./television/livebox.pressKey'),
    openMenu : require('./television/livebox.openMenu'),
    openInfo : require('./television/livebox.openInfo'),
    rec : require('./television/livebox.rec'),
    yellowButton : require('./television/livebox.yellowButton'),
    skipNext : require('./television/livebox.skipNext'),
    skipPrevious : require('./television/livebox.skipPrevious')
};
